version: "3.8"
services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    # command: /bin/sh -c "while sleep 1000; do :; done" # only for debugging
