# fly.toml app configuration file generated for hackathon-int20h-2024 on 2024-02-10T20:55:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hackathon-int20h-2024'
primary_region = 'waw'

[build]

[http_service]
internal_port = 4001
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
